# build-ffmpeg.ps1
#
# Builds the minimal ffmpeg sidecar (~15-25 MB vs the ~231 MB Gyan full_build) via
# media-autobuild_suite. The verified output is hosted as a pinned GitHub release asset
# that get-ffmpeg.ps1 downloads; this script is only needed to (re)produce that asset,
# not by regular clones or CI.
#
# The component list below mirrors exactly what the app uses (see docs/SPEC_FFMPEG.md
# and src-tauri/src/stream/pipeline.rs). WHIP needs ffmpeg 8.x with a real DTLS backend:
# we use GnuTLS (the suite's GPL license choice disables OpenSSL; GnuTLS matches the
# proven Gyan pin). Never --enable-nonfree: the output must stay redistributable.
# Suite license prompt: answer 2 (GPLv3 - keeps gmp, which GnuTLS needs); 64-bit only.
# Note: `-f lavfi` (ddagrab/anullsrc inputs) is an avdevice *indev*, so avdevice must
# stay enabled; gdigrab/dshow are dropped (unused since the WGC/rawvideo-pipe rework).
#
# Prerequisites:
#   - Git in PATH
#   - media-autobuild_suite cloned:
#       git clone https://github.com/m-ab-s/media-autobuild_suite.git C:\media-autobuild_suite
#     (first run is interactive: MSYS2 bootstrap + toolchain prompts, ~10 GB disk, 20-60 min)
#
# Usage:
#   .\build-ffmpeg.ps1 -SuitePath "C:\media-autobuild_suite"
#   .\build-ffmpeg.ps1 -SuitePath "C:\media-autobuild_suite" -InstallOnly
#     (skip the build; just copy/strip/install an already-built local64\bin-video\ffmpeg.exe —
#      needed after a first run, where the suite detaches the compile into a mintty window)

param(
    [Parameter(Mandatory = $true)]
    [string]$SuitePath,
    [switch]$InstallOnly
)

$ErrorActionPreference = "Stop"

# --- Paths ---
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TauriDir = Split-Path -Parent $ScriptDir
$BinariesDir = Join-Path $TauriDir "binaries"
$TargetBinary = Join-Path $BinariesDir "ffmpeg-x86_64-pc-windows-msvc.exe"

Write-Host ""
Write-Host "Speedrace - minimal ffmpeg sidecar builder" -ForegroundColor Cyan
Write-Host "Output: $TargetBinary"
Write-Host ""

$SuitePath = $SuitePath.Trim().Trim('"', "'").Trim()
if (-not (Test-Path $SuitePath)) {
    Write-Host "ERROR: Path does not exist: $SuitePath" -ForegroundColor Red
    Write-Host "Clone it first:" -ForegroundColor Yellow
    Write-Host "  git clone https://github.com/m-ab-s/media-autobuild_suite.git `"$SuitePath`"" -ForegroundColor Green
    exit 1
}

if ($InstallOnly) {
    Write-Host "InstallOnly: skipping build, installing existing suite output..." -ForegroundColor Cyan
} else {

# --- Step 1: Update media-autobuild_suite ---

Push-Location $SuitePath
try {
    Write-Host "Updating media-autobuild_suite (git pull)..."
    git pull --ff-only
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: git pull failed. Continuing with current version..." -ForegroundColor Yellow
    }
} finally {
    Pop-Location
}

# --- Step 2: Write ffmpeg_options.txt ---

$BuildDir = Join-Path $SuitePath "build"
if (-not (Test-Path $BuildDir)) {
    New-Item -ItemType Directory -Path $BuildDir -Force | Out-Null
}

$OptionsFile = Join-Path $BuildDir "ffmpeg_options.txt"
if (Test-Path $OptionsFile) {
    Copy-Item $OptionsFile "$OptionsFile.bak" -Force
    Write-Host "Backed up existing options to ffmpeg_options.txt.bak"
}

$FfmpegOptions = @"
# Speedrace minimal ffmpeg build
# Auto-generated by build-ffmpeg.ps1 - do not edit manually.
# Component inventory source: speedrace-app docs/SPEC_FFMPEG.md + src/stream/pipeline.rs

--enable-gpl
--enable-version3

# Strip to nothing, re-enable exactly what the app uses
--disable-everything
--disable-autodetect
--disable-doc
--disable-htmlpages
--disable-manpages
--disable-podpages
--disable-txtpages
--disable-programs
--enable-ffmpeg
--enable-network
--enable-small

# External libraries (GnuTLS = the DTLS backend the whip muxer needs; the suite's
# GPL license choice disables OpenSSL, and GnuTLS matches the proven Gyan build)
--enable-libx264
--enable-libopus
--enable-gnutls

# Hardware (d3d11va is a ddagrab dependency; nvenc/amf are header-only, compiled in
# for the planned hw-encode follow-up). ffnvcodec is explicit because --disable-autodetect
# also stops the suite from installing the nv-codec-headers nvenc needs.
--enable-d3d11va
--enable-ffnvcodec
--enable-nvenc
--enable-amf

# Encoders (mjpeg serves the mpjpeg preview + monitor thumbnails)
--enable-encoder=libx264
--enable-encoder=h264_nvenc
--enable-encoder=h264_amf
--enable-encoder=libopus
--enable-encoder=aac
--enable-encoder=mjpeg

# Decoders (the app never decodes h264/aac; inputs are raw pipes). The lavfi indev
# wraps its outputs: ddagrab frames arrive as wrapped_avframe, anullsrc as pcm_u8.
--enable-decoder=rawvideo
--enable-decoder=pcm_f32le
--enable-decoder=wrapped_avframe
--enable-decoder=pcm_u8

# Muxers
--enable-muxer=whip
--enable-muxer=mp4
--enable-muxer=mpjpeg
--enable-muxer=mjpeg

# Input: lavfi indev (ddagrab/anullsrc via -f lavfi) + raw pipes
--enable-indev=lavfi
--enable-demuxer=rawvideo
--enable-demuxer=pcm_f32le

# Parsers
--enable-parser=h264
--enable-parser=aac
--enable-parser=opus

# Protocols (dtls+srtp+rtp = WHIP; http/https = the WHIP POST endpoint)
--enable-protocol=file
--enable-protocol=pipe
--enable-protocol=http
--enable-protocol=https
--enable-protocol=tcp
--enable-protocol=udp
--enable-protocol=tls
--enable-protocol=dtls
--enable-protocol=srtp
--enable-protocol=rtp
--enable-protocol=crypto

# Filters
--enable-filter=ddagrab
--enable-filter=hwdownload
--enable-filter=format
--enable-filter=scale
--enable-filter=aresample
--enable-filter=anullsrc
--enable-filter=split
--enable-filter=asplit
--enable-filter=null
--enable-filter=anull

# Bitstream filters
--enable-bsf=h264_mp4toannexb
--enable-bsf=aac_adtstoasc
--enable-bsf=extract_extradata

# Optimizations
--enable-optimizations
--enable-stripping
--disable-debug
--extra-cflags=-O2
--extra-ldflags=-s
"@

# BOM-less on purpose: PS5's UTF8 writes a BOM, which ffmpeg configure rejects as an option
[System.IO.File]::WriteAllText($OptionsFile, $FfmpegOptions.Replace("`r`n", "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "Written: $OptionsFile" -ForegroundColor Green

# Seed the suite's answer file from our checked-in snapshot so a fresh machine
# skips every interactive prompt (GPLv3, 64-bit, x264 8-bit, static ffmpeg, no tools).
$IniFile = Join-Path $BuildDir "media-autobuild_suite.ini"
$IniSnapshot = Join-Path $ScriptDir "media-autobuild_suite.ini"
if (-not (Test-Path $IniFile)) {
    Copy-Item $IniSnapshot $IniFile
    Write-Host "Seeded suite answers from: $IniSnapshot" -ForegroundColor Green
}

# --- Step 3: Run the build ---

$BatFile = Join-Path $SuitePath "media-autobuild_suite.bat"
if (-not (Test-Path $BatFile)) {
    Write-Host "ERROR: Cannot find media-autobuild_suite.bat at: $BatFile" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Starting the build (first run 20-60 min, incremental ~5-10 min)..." -ForegroundColor Cyan

# The suite refuses to run inside an MSVC environment (VS dev shells put cl.exe/lib.exe
# in PATH); strip those entries and the MSVC env vars for the child process only.
function Test-DirHasTool([string]$dir, [string]$tool) {
    try { Test-Path -LiteralPath (Join-Path $dir $tool) -ErrorAction SilentlyContinue } catch { $false }
}
$CleanPath = ($env:PATH -split ';' | Where-Object {
    $_ -and -not (Test-DirHasTool $_ 'cl.exe') -and -not (Test-DirHasTool $_ 'lib.exe')
}) -join ';'

$Saved = @{}
foreach ($v in 'PATH', 'LIB', 'INCLUDE', 'LIBPATH', 'VSINSTALLDIR') {
    $Saved[$v] = [Environment]::GetEnvironmentVariable($v)
}
Push-Location $SuitePath
try {
    $env:PATH = $CleanPath
    $env:LIB = $null; $env:INCLUDE = $null; $env:LIBPATH = $null; $env:VSINSTALLDIR = $null
    & cmd /c $BatFile
    if ($LASTEXITCODE -ne 0) {
        # With mintty enabled the .bat detaches the compile into a mintty window and
        # returns nonzero from the console part — not a build failure.
        Write-Host "NOTE: launcher exited with code $LASTEXITCODE." -ForegroundColor Yellow
        Write-Host "If a mintty window is still compiling, wait for it, then re-run with -InstallOnly." -ForegroundColor Yellow
    }
} finally {
    foreach ($v in $Saved.Keys) {
        [Environment]::SetEnvironmentVariable($v, $Saved[$v])
    }
    Pop-Location
}

}  # end if (-not $InstallOnly)

# --- Step 4: Locate and install the built ffmpeg.exe ---

$PossiblePaths = @(
    (Join-Path $SuitePath "local64\bin-video\ffmpeg.exe"),
    (Join-Path $SuitePath "local64\bin\ffmpeg.exe")
)
$BuiltFfmpeg = $PossiblePaths | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $BuiltFfmpeg) {
    Write-Host "ERROR: built ffmpeg.exe not found in:" -ForegroundColor Red
    $PossiblePaths | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host "If the mintty window is still compiling, wait for it to finish, then re-run:" -ForegroundColor Yellow
    Write-Host "  .\build-ffmpeg.ps1 -SuitePath `"$SuitePath`" -InstallOnly" -ForegroundColor Green
    exit 1
}

if (-not (Test-Path $BinariesDir)) {
    New-Item -ItemType Directory -Path $BinariesDir -Force | Out-Null
}
Copy-Item $BuiltFfmpeg $TargetBinary -Force

$StripExe = Get-Command "strip" -ErrorAction SilentlyContinue
if ($StripExe) {
    & strip --strip-all $TargetBinary
} else {
    Write-Host "SKIP: 'strip' not in PATH (add MSYS2 mingw64\bin for a smaller binary)" -ForegroundColor Yellow
}
# No UPX on purpose: packed exes trigger AV false positives on end-user machines.

$FinalSize = [math]::Round((Get-Item $TargetBinary).Length / 1MB, 1)
Write-Host ""
Write-Host "Installed: $TargetBinary ($FinalSize MB)" -ForegroundColor Green
Write-Host ""
Write-Host "Verify before shipping (all must pass):" -ForegroundColor Yellow
Write-Host "  & `"$TargetBinary`" -hide_banner -buildconf   # expect --enable-gnutls, NO --enable-nonfree"
Write-Host "  & `"$TargetBinary`" -hide_banner -protocols   # expect BOTH dtls and srtp"
Write-Host "  & `"$TargetBinary`" -hide_banner -muxers 2>&1    | Select-String 'whip|mp4|mpjpeg'"
Write-Host "  & `"$TargetBinary`" -hide_banner -encoders 2>&1  | Select-String 'libx264|libopus|aac|mjpeg|nvenc|amf'"
Write-Host "  & `"$TargetBinary`" -hide_banner -filters 2>&1   | Select-String 'ddagrab|hwdownload|split|aresample'"
Write-Host ""
Write-Host "Then run the runtime drills in docs/SPEC_FFMPEG.md (preview, Publish, MP4 replay)."
Write-Host "Once verified, zip + upload as the pinned release asset and re-pin get-ffmpeg.ps1."
