# build-ffmpeg.ps1
# One-shot script to build a minimal ffmpeg for the Momentum Tauri sidecar.
# Run this on Windows. The output goes directly to src-tauri/binaries/.
#
# Prerequisites:
#   - Git installed and in PATH
#   - (Optional) UPX installed for compression: winget install upx
#
# Usage:
#   .\build-ffmpeg.ps1
#   .\build-ffmpeg.ps1 -SuitePath "C:\path\to\media-autobuild_suite"

param(
    [string]$SuitePath
)

$ErrorActionPreference = "Stop"

# --- Paths ---
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TauriDir = Split-Path -Parent $ScriptDir
$BinariesDir = Join-Path $TauriDir "binaries"
$TargetBinary = Join-Path $BinariesDir "ffmpeg-x86_64-pc-windows-msvc.exe"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Momentum — Minimal ffmpeg Builder" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This script builds a minimal ffmpeg (~15-20MB) with only the"
Write-Host "components needed for screen capture + WHIP streaming + MP4 recording."
Write-Host ""
Write-Host "Output: $TargetBinary"
Write-Host ""

# --- Step 1: Locate or clone media-autobuild_suite ---

if (-not $SuitePath) {
    Write-Host "-------------------------------------------" -ForegroundColor Yellow
    Write-Host "  Step 1: media-autobuild_suite location" -ForegroundColor Yellow
    Write-Host "-------------------------------------------" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "If you haven't cloned it yet, run this first:"
    Write-Host ""
    Write-Host "  git clone https://github.com/m-ab-s/media-autobuild_suite.git C:\media-autobuild_suite" -ForegroundColor Green
    Write-Host ""
    Write-Host "Then provide the path below."
    Write-Host ""

    $SuitePath = Read-Host "Path to media-autobuild_suite folder"
}

$SuitePath = $SuitePath.Trim('"').Trim("'")

if (-not (Test-Path $SuitePath)) {
    Write-Host "ERROR: Path does not exist: $SuitePath" -ForegroundColor Red
    Write-Host ""
    Write-Host "Clone it first:" -ForegroundColor Yellow
    Write-Host "  git clone https://github.com/m-ab-s/media-autobuild_suite.git `"$SuitePath`"" -ForegroundColor Green
    exit 1
}

# --- Step 2: Git pull latest ---

Write-Host ""
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host "  Step 2: Updating media-autobuild_suite" -ForegroundColor Yellow
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host ""

Push-Location $SuitePath
try {
    Write-Host "Running git pull..."
    git pull --ff-only
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: git pull failed. Continuing with current version..." -ForegroundColor Yellow
    } else {
        Write-Host "Updated to latest." -ForegroundColor Green
    }
} finally {
    Pop-Location
}

# --- Step 3: Write ffmpeg_options.txt ---

Write-Host ""
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host "  Step 3: Writing ffmpeg build options" -ForegroundColor Yellow
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host ""

$BuildDir = Join-Path $SuitePath "build"
if (-not (Test-Path $BuildDir)) {
    New-Item -ItemType Directory -Path $BuildDir -Force | Out-Null
}

$OptionsFile = Join-Path $BuildDir "ffmpeg_options.txt"

# Back up existing options if present
if (Test-Path $OptionsFile) {
    $BackupFile = Join-Path $BuildDir "ffmpeg_options.txt.bak"
    Copy-Item $OptionsFile $BackupFile -Force
    Write-Host "Backed up existing options to ffmpeg_options.txt.bak"
}

$FfmpegOptions = @"
# Momentum minimal ffmpeg build
# Auto-generated by build-ffmpeg.ps1 — do not edit manually

--enable-gpl
--enable-nonfree
--enable-version3

# Disable everything, re-enable selectively
--disable-everything
--disable-doc
--disable-htmlpages
--disable-manpages
--disable-podpages
--disable-txtpages
--disable-autodetect
--disable-programs
--disable-avdevice

# Re-enable core
--enable-ffmpeg
--enable-network
--enable-small

# External libraries
--enable-libx264
--enable-libopus
--enable-openssl

# Hardware acceleration (Windows)
--enable-d3d11va
--enable-dxva2
--enable-nvenc
--enable-amf
--enable-libmfx

# Encoders
--enable-encoder=libx264
--enable-encoder=h264_nvenc
--enable-encoder=h264_qsv
--enable-encoder=h264_amf
--enable-encoder=h264_mf
--enable-encoder=libopus
--enable-encoder=aac
--enable-encoder=pcm_f32le

# Decoders
--enable-decoder=rawvideo
--enable-decoder=pcm_f32le
--enable-decoder=pcm_s16le
--enable-decoder=h264
--enable-decoder=aac

# Muxers
--enable-muxer=whip
--enable-muxer=mp4
--enable-muxer=mov
--enable-muxer=null
--enable-muxer=rawvideo

# Demuxers
--enable-demuxer=lavfi
--enable-demuxer=rawvideo
--enable-demuxer=pcm_f32le
--enable-demuxer=pcm_s16le
--enable-demuxer=mov
--enable-demuxer=concat

# Parsers
--enable-parser=h264
--enable-parser=aac
--enable-parser=opus

# Protocols
--enable-protocol=file
--enable-protocol=pipe
--enable-protocol=http
--enable-protocol=https
--enable-protocol=udp
--enable-protocol=tcp
--enable-protocol=tls
--enable-protocol=crypto
--enable-protocol=rtp
--enable-protocol=srtp

# Filters
--enable-filter=ddagrab
--enable-filter=hwdownload
--enable-filter=hwupload
--enable-filter=format
--enable-filter=scale
--enable-filter=scale_cuda
--enable-filter=null
--enable-filter=anull
--enable-filter=aresample
--enable-filter=aformat
--enable-filter=abuffer
--enable-filter=buffer
--enable-filter=abuffersink
--enable-filter=buffersink
--enable-filter=setpts
--enable-filter=asetpts
--enable-filter=trim
--enable-filter=atrim
--enable-filter=split
--enable-filter=asplit

# Bitstream filters
--enable-bsf=h264_mp4toannexb
--enable-bsf=aac_adtstoasc
--enable-bsf=null

# Input devices (Windows)
--enable-indev=gdigrab
--enable-indev=dshow

# Optimizations
--enable-optimizations
--enable-stripping
--disable-debug
--extra-cflags=-O2
--extra-ldflags=-s
"@

Set-Content -Path $OptionsFile -Value $FfmpegOptions -Encoding UTF8
Write-Host "Written: $OptionsFile" -ForegroundColor Green

# Also write media-autobuild_suite.ini for non-interactive mode if it doesn't exist
$IniFile = Join-Path $BuildDir "media-autobuild_suite.ini"
if (-not (Test-Path $IniFile)) {
    Write-Host ""
    Write-Host "NOTE: First run of media-autobuild_suite will be interactive." -ForegroundColor Yellow
    Write-Host "It will ask you setup questions (MSYS2 install, toolchain, etc.)." -ForegroundColor Yellow
    Write-Host "After the first run, subsequent builds are automatic." -ForegroundColor Yellow
}

# --- Step 4: Run the build ---

Write-Host ""
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host "  Step 4: Running media-autobuild_suite" -ForegroundColor Yellow
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host ""
Write-Host "Starting the build. This will take 20-60 minutes on first run"
Write-Host "(downloads + compiles all dependencies: x264, opus, openssl, ffmpeg)."
Write-Host ""
Write-Host "On subsequent runs it only rebuilds what changed (~5-10 min)."
Write-Host ""

$BatFile = Join-Path $SuitePath "media-autobuild_suite.bat"
if (-not (Test-Path $BatFile)) {
    Write-Host "ERROR: Cannot find media-autobuild_suite.bat at: $BatFile" -ForegroundColor Red
    exit 1
}

# Run the build
Push-Location $SuitePath
try {
    & cmd /c $BatFile
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Build failed with exit code $LASTEXITCODE" -ForegroundColor Red
        exit 1
    }
} finally {
    Pop-Location
}

# --- Step 5: Find the built ffmpeg.exe ---

Write-Host ""
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host "  Step 5: Locating built ffmpeg.exe" -ForegroundColor Yellow
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host ""

# media-autobuild_suite outputs to local64/bin-video/ or local64/bin/
$PossiblePaths = @(
    (Join-Path $SuitePath "local64\bin-video\ffmpeg.exe"),
    (Join-Path $SuitePath "local64\bin\ffmpeg.exe"),
    (Join-Path $SuitePath "local32\bin-video\ffmpeg.exe")
)

$BuiltFfmpeg = $null
foreach ($p in $PossiblePaths) {
    if (Test-Path $p) {
        $BuiltFfmpeg = $p
        break
    }
}

if (-not $BuiltFfmpeg) {
    Write-Host "ERROR: Could not find built ffmpeg.exe in expected locations:" -ForegroundColor Red
    foreach ($p in $PossiblePaths) {
        Write-Host "  - $p" -ForegroundColor Red
    }
    Write-Host ""
    Write-Host "Check the build output above for errors." -ForegroundColor Yellow
    exit 1
}

Write-Host "Found: $BuiltFfmpeg" -ForegroundColor Green
$OriginalSize = (Get-Item $BuiltFfmpeg).Length / 1MB
Write-Host "Size: $([math]::Round($OriginalSize, 1)) MB"

# --- Step 6: Post-build optimization ---

Write-Host ""
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host "  Step 6: Post-build optimization" -ForegroundColor Yellow
Write-Host "-------------------------------------------" -ForegroundColor Yellow
Write-Host ""

# Create binaries directory if it doesn't exist
if (-not (Test-Path $BinariesDir)) {
    New-Item -ItemType Directory -Path $BinariesDir -Force | Out-Null
}

# Copy to target location first
Copy-Item $BuiltFfmpeg $TargetBinary -Force
Write-Host "Copied to: $TargetBinary"

# Try to strip (if strip is available via MSYS2 in PATH)
$StripExe = Get-Command "strip" -ErrorAction SilentlyContinue
if ($StripExe) {
    Write-Host "Stripping debug symbols..."
    & strip --strip-all $TargetBinary
    $StrippedSize = (Get-Item $TargetBinary).Length / 1MB
    Write-Host "Size after strip: $([math]::Round($StrippedSize, 1)) MB" -ForegroundColor Green
} else {
    Write-Host "SKIP: 'strip' not found in PATH (add MSYS2/mingw64/bin to PATH for stripping)" -ForegroundColor Yellow
}

# Try UPX compression (optional)
$UpxExe = Get-Command "upx" -ErrorAction SilentlyContinue
if ($UpxExe) {
    Write-Host "Compressing with UPX..."
    & upx --best --lzma $TargetBinary
    $FinalSize = (Get-Item $TargetBinary).Length / 1MB
    Write-Host "Size after UPX: $([math]::Round($FinalSize, 1)) MB" -ForegroundColor Green
} else {
    Write-Host "SKIP: 'upx' not found. Install with: winget install upx" -ForegroundColor Yellow
    Write-Host "      UPX can reduce size by ~50% but some AV may flag it." -ForegroundColor Yellow
}

# --- Step 7: Summary ---

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Done!" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

$FinalSize = (Get-Item $TargetBinary).Length / 1MB
Write-Host "  Binary: $TargetBinary" -ForegroundColor Green
Write-Host "  Size:   $([math]::Round($FinalSize, 1)) MB" -ForegroundColor Green
Write-Host ""
Write-Host "  The ffmpeg sidecar is ready. Tauri will bundle it automatically"
Write-Host "  on the next build (cargo tauri build)."
Write-Host ""
Write-Host "  Verify it works:" -ForegroundColor Yellow
Write-Host "    & `"$TargetBinary`" -hide_banner -encoders 2>&1 | Select-String 'libx264|h264_nvenc|libopus|aac'"
Write-Host "    & `"$TargetBinary`" -hide_banner -muxers 2>&1 | Select-String 'whip|mp4'"
Write-Host "    & `"$TargetBinary`" -hide_banner -filters 2>&1 | Select-String 'ddagrab|scale|hwdownload'"
Write-Host ""
